[profile.release]
opt-level = "s"
lto = true

[package]
name = "Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.10"
serde_json = "1.0.145"
hex = "0.4.3"
rand = "0.9.2"
byteorder = "1.5.0"
chrono = "0.4.42"


